version: '3.8'
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-farmacia
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: farmacia
      MARIADB_USER: farmaciauser
      MARIADB_PASSWORD: farmaciapass
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"